services:
  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html